package software.aoc.day07.b;

import org.junit.Test;

import java.io.IOException;
import java.io.InputStream;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

public class QuantumManifoldTest {
    private static final String input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    public void counts_the_total_number_of_timelines() {
        QuantumManifold manifold = QuantumManifold.from(input);

        assertThat(manifold.countTimelines()).isEqualTo(40);
    }

    @Test
    public void answer() throws IOException {
        try (InputStream inputStream = QuantumManifold.class.getResourceAsStream("/day07/input.txt")) {
            QuantumManifold manifold = QuantumManifold.from(new String(inputStream != null ? inputStream.readAllBytes() : null));
            assertThat(manifold.countTimelines()).isEqualTo(171692855075500L);
        }
    }
}
