package software.aoc.day07.a;

import org.junit.Test;

import java.io.IOException;
import java.io.InputStream;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

public class TachyonManifoldTest {
    private static final String input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    public void count_the_total_number_of_splits() {
        TachyonManifold manifold = TachyonManifold.from(input);

        assertThat(manifold.countSplits()).isEqualTo(21);
    }

    @Test
    public void answer() throws IOException {
        try (InputStream inputStream = TachyonManifold.class.getResourceAsStream("/day07/input.txt")) {
            TachyonManifold manifold = TachyonManifold.from(new String(inputStream != null ? inputStream.readAllBytes() : null));
            assertThat(manifold.countSplits()).isEqualTo(1703);
        }
    }
}
